In [108]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [109]:

df1=pd.read_csv("df_Customers.csv")
df2=pd.read_csv("df_OrderItems.csv")
df3=pd.read_csv("df_Orders.csv")
df4=pd.read_csv("df_Payments.csv")
df5=pd.read_csv("df_Products.csv")# as utf-8 was not able to encode some strings in the data we converted it to latin1

In [110]:
df3.head(16)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18
5,VjTVGzqe8U6R,UkqnhxmX7YMP,delivered,2017-09-01 14:38:16,2017-09-01 14:50:24,2017-09-15 18:57:50,2017-09-26
6,xNba906m4TM1,85jiDiGSfhTu,delivered,2018-04-23 21:03:00,2018-04-24 18:18:18,2018-04-25 20:14:38,2018-05-04
7,VEDSMTavbQwk,gDdkaN8b9s1g,delivered,2018-02-23 14:49:39,2018-02-23 15:16:13,2018-04-02 14:12:50,2018-03-15
8,DzNM8wrcMGFH,9Csx6oXlpLl1,delivered,2017-11-24 19:12:37,2017-11-25 04:54:03,2017-12-11 13:09:32,2017-12-14
9,NpJz7zF9U1ae,gZTPKLPRnreg,delivered,2017-11-30 11:48:21,2017-11-30 13:31:19,2017-12-14 16:38:47,2018-01-03
10,mHyhzcUeLGj2,TDEBQrhIwApB,delivered,2018-04-02 22:39:59,2018-04-03 22:35:18,2018-04-13 18:12:30,2018-04-23
11,StM5K4TLyrt5,1k71TCYNFCzj,delivered,2018-05-30 09:25:25,2018-05-30 09:35:16,2018-06-21 18:22:15,2018-07-05
12,Q97dFuo1kaq9,IfWKDQHkjLDd,delivered,2018-04-10 00:17:56,2018-04-10 00:35:11,2018-04-20 18:03:58,2018-05-04
13,07j6mlMhSVtx,kZ0rkJCJ6N5y,delivered,2018-05-02 22:52:10,2018-05-03 00:13:21,2018-05-09 23:48:32,2018-05-18
14,kxa1InBj9gwP,zsCKIdqYLV01,delivered,2017-04-24 20:06:41,2017-04-24 20:22:24,2017-05-05 10:22:27,2017-05-25
15,P5R6jr1qZdh4,FrEvnEiMKGpr,canceled,2017-07-24 11:38:43,2017-07-24 11:50:18,NaN,2017-08-07

In [111]:
df5.shape

(89316, 6)

In [112]:
df3.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

In [113]:
df5.isnull().sum()

product_id                 0
product_category_name    308
product_weight_g          15
product_length_cm         15
product_height_cm         15
product_width_cm          15
dtype: int64

In [114]:
df3[df3['order_delivered_timestamp'].isnull()]['order_status'].value_counts

<bound method IndexOpsMixin.value_counts of 15       canceled
41        shipped
86        shipped
89       canceled
133      canceled
           ...
89196     shipped
89226    canceled
89234     shipped
89262    canceled
89281     shipped
Name: order_status, Length: 1889, dtype: object>

In [115]:
df5['product_category_name'].fillna('Unknown',inplace=True)

C:\Users\Hamza\AppData\Local\Temp\ipykernel_16716\3691235290.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5['product_category_name'].fillna('Unknown',inplace=True)

In [116]:
df5['product_category_name'].unique()

array(['toys', 'watches_gifts', 'costruction_tools_garden',
       'bed_bath_table', 'auto', 'health_beauty', 'cool_stuff',
       'garden_tools', 'furniture_decor', 'fashion_shoes',
       'sports_leisure', 'baby', 'housewares',
       'construction_tools_construction', 'electronics',
       'home_appliances', 'audio', 'consoles_games', 'stationery',
       'furniture_living_room', 'computers_accessories', 'perfumery',
       'kitchen_dining_laundry_garden_furniture',
       'fashion_bags_accessories', 'market_place', 'telephony',
       'home_construction', 'Unknown', 'office_furniture',
       'industry_commerce_and_business', 'food_drink', 'drinks',
       'agro_industry_and_commerce', 'signaling_and_security', 'food',
       'pet_shop', 'luggage_accessories', 'home_appliances_2',
       'small_appliances', 'tablets_printing_image',
       'construction_tools_lights', 'musical_instruments', 'home_confort',
       'air_conditioning', 'construction_tools_safety',
       'costruction_tools_tools', 'books_technical',
       'books_general_interest', 'books_imported', 'computers',
       'cine_photo', 'music', 'fashion_male_clothing', 'fashion_sport',
       'fixed_telephony', 'fashion_underwear_beach', 'furniture_bedroom',
       'art', 'christmas_supplies', 'dvds_blu_ray', 'flowers',
       'la_cuisine', 'furniture_mattress_and_upholstery',
       'small_appliances_home_oven_and_coffee', 'home_comfort_2',
       'arts_and_craftmanship', 'party_supplies',
       'fashion_childrens_clothes', 'fashio_female_clothing',
       'security_and_services', 'diapers_and_hygiene'], dtype=object)

In [117]:
df5['product_weight_g'].fillna(df5.groupby('product_category_name')['product_weight_g'].transform('median'),inplace=True)
#It replaces each null with the median weight,width,height,length,weight of that specific category

C:\Users\Hamza\AppData\Local\Temp\ipykernel_16716\3990841773.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5['product_weight_g'].fillna(df5.groupby('product_category_name')['product_weight_g'].transform('median'),inplace=True)

In [118]:
df5['product_width_cm'].fillna(df5.groupby('product_category_name')['product_width_cm'].transform('median'),inplace=True)

C:\Users\Hamza\AppData\Local\Temp\ipykernel_16716\522063125.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5['product_width_cm'].fillna(df5.groupby('product_category_name')['product_width_cm'].transform('median'),inplace=True)

In [119]:
df5['product_height_cm'].fillna(df5.groupby('product_category_name')['product_height_cm'].transform('median'),inplace=True)

C:\Users\Hamza\AppData\Local\Temp\ipykernel_16716\2812215579.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5['product_height_cm'].fillna(df5.groupby('product_category_name')['product_height_cm'].transform('median'),inplace=True)

In [120]:
df5['product_length_cm'].fillna(df5.groupby('product_category_name')['product_length_cm'].transform('median'),inplace=True)

C:\Users\Hamza\AppData\Local\Temp\ipykernel_16716\4116924610.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df5['product_length_cm'].fillna(df5.groupby('product_category_name')['product_length_cm'].transform('median'),inplace=True)

In [121]:
df3.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                   9
order_delivered_timestamp        1889
order_estimated_delivery_date       0
dtype: int64

In [122]:
df3.dropna(subset=['order_approved_at'],inplace=True)

In [123]:
df3['order_approved_at'].isnull().sum()

np.int64(0)

In [124]:
df4[df4['payment_value']==-1]

Empty DataFrame
Columns: [order_id, payment_sequential, payment_type, payment_installments, payment_value]
Index: []

In [125]:
df1['customer_city'].value_counts().tail()

customer_city
unistalda               1
matriz de camaragibe    1
cipo-guacu              1
pendencias              1
aramari                 1
Name: count, dtype: int64

In [126]:
df1['customer_city'].value_counts().head()

customer_city
sao paulo         14352
rio de janeiro     6248
belo horizonte     2426
brasilia           1778
curitiba           1421
Name: count, dtype: int64

In [127]:
avg_shipping_charge=df2['shipping_charges'].mean().round(2)
print(avg_shipping_charge,"BRL")

44.28 BRL

In [128]:
avg_price=df2['price'].mean().round(3)
print(avg_price,"BRL")

340.901 BRL

In [129]:
# df1.to_csv('C:/Users/Hamza/Downloads/Cleaned Data/cleaned_customer_data_utf8.csv', index=False, encoding='utf-8')
# df2.to_csv('C:/Users/Hamza/Downloads/Cleaned Data/cleaned_order_items_utf8.csv', index=False, encoding='utf-8')
# df3.to_csv('C:/Users/Hamza/Downloads/Cleaned Data/cleaned_orders_data_utf8.csv', index=False, encoding='utf-8')
# df4.to_csv('C:/Users/Hamza/Downloads/Cleaned Data/cleaned_payments_data_utf8.csv', index=False, encoding='utf-8')
# df5.to_csv('C:/Users/Hamza/Downloads/Cleaned Data/cleaned_products_data_utf8.csv', index=False, encoding='utf-8')

In [130]:
df3.head(18)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_timestamp,order_estimated_delivery_date
0,Axfy13Hk4PIk,hCT0x9JiGXBQ,delivered,2017-10-22 18:57:54,2017-10-22 19:14:13,2017-10-26 22:19:52,2017-11-09
1,v6px92oS8cLG,PxA7fv9spyhx,delivered,2018-06-20 21:40:31,2018-06-20 22:20:20,2018-07-03 22:51:22,2018-07-24
2,Ulpf9skrhjfm,g3nXeJkGI0Qw,delivered,2018-02-16 16:19:31,2018-02-17 16:15:35,2018-02-27 01:29:50,2018-03-08
3,bwJVWupf2keN,EOEsCQ6QlpIg,delivered,2018-08-18 18:04:29,2018-08-18 18:15:16,2018-08-27 20:03:51,2018-09-19
4,Dd0QnrMk9Cj5,mVz5LO2Vd6cL,delivered,2017-12-22 16:44:04,2017-12-22 17:31:31,2018-01-05 19:22:49,2018-01-18
5,VjTVGzqe8U6R,UkqnhxmX7YMP,delivered,2017-09-01 14:38:16,2017-09-01 14:50:24,2017-09-15 18:57:50,2017-09-26
6,xNba906m4TM1,85jiDiGSfhTu,delivered,2018-04-23 21:03:00,2018-04-24 18:18:18,2018-04-25 20:14:38,2018-05-04
7,VEDSMTavbQwk,gDdkaN8b9s1g,delivered,2018-02-23 14:49:39,2018-02-23 15:16:13,2018-04-02 14:12:50,2018-03-15
8,DzNM8wrcMGFH,9Csx6oXlpLl1,delivered,2017-11-24 19:12:37,2017-11-25 04:54:03,2017-12-11 13:09:32,2017-12-14
9,NpJz7zF9U1ae,gZTPKLPRnreg,delivered,2017-11-30 11:48:21,2017-11-30 13:31:19,2017-12-14 16:38:47,2018-01-03
10,mHyhzcUeLGj2,TDEBQrhIwApB,delivered,2018-04-02 22:39:59,2018-04-03 22:35:18,2018-04-13 18:12:30,2018-04-23
11,StM5K4TLyrt5,1k71TCYNFCzj,delivered,2018-05-30 09:25:25,2018-05-30 09:35:16,2018-06-21 18:22:15,2018-07-05
12,Q97dFuo1kaq9,IfWKDQHkjLDd,delivered,2018-04-10 00:17:56,2018-04-10 00:35:11,2018-04-20 18:03:58,2018-05-04
13,07j6mlMhSVtx,kZ0rkJCJ6N5y,delivered,2018-05-02 22:52:10,2018-05-03 00:13:21,2018-05-09 23:48:32,2018-05-18
14,kxa1InBj9gwP,zsCKIdqYLV01,delivered,2017-04-24 20:06:41,2017-04-24 20:22:24,2017-05-05 10:22:27,2017-05-25
15,P5R6jr1qZdh4,FrEvnEiMKGpr,canceled,2017-07-24 11:38:43,2017-07-24 11:50:18,NaN,2017-08-07
16,HqV5f8K2UYoA,3zvaY9gUH9bO,delivered,2018-06-15 15:44:21,2018-06-15 16:00:22,2018-06-25 22:27:56,2018-07-11
17,j5rwgECNf14O,bUornDCZmRD4,delivered,2018-03-15 11:13:23,2018-03-15 11:29:14,2018-04-09 18:54:36,2018-04-03

In [131]:
df3['order_status'].unique()

array(['delivered', 'canceled', 'shipped', 'processing', 'invoiced',
       'unavailable', 'approved'], dtype=object)

<h2>Total Null Values in the orders table group by order status

approved       → 2 <br>
canceled       → 404 <br>
delivered      → 6 <br>
invoiced       → 266 <br>
processing     → 273 <br>
shipped        → 936 <br>
unavailable    → 2 <br>

In [132]:
# Cancelled orders → drop the rows (they'll never be delivered)
# Shipped orders → fill with estimated delivery date
# Processing orders → fill with estimated delivery date
# approved orders → fill with estimated delivery date
# invoiced orders → fill with estimated delivery date 
# delivered → fill with estimated delivery date 
# unavailable → drop the rows

df3 = df3[~((df3['order_status'] == 'canceled') & (df3['order_delivered_timestamp'].isnull()))]

df3.loc[
    (df3['order_status'] == 'shipped') & (df3['order_delivered_timestamp'].isnull()),
    'order_delivered_timestamp'
] = df3['order_estimated_delivery_date']

df3.loc[
    (df3['order_status'] == 'processing') & (df3['order_delivered_timestamp'].isnull()),
    'order_delivered_timestamp'
] = df3['order_estimated_delivery_date']

fill_statuses = ['shipped', 'processing', 'approved', 'invoiced', 'delivered']

df3.loc[
    (df3['order_status'].isin(fill_statuses)) & (df3['order_delivered_timestamp'].isnull()),
    'order_delivered_timestamp'
] = df3['order_estimated_delivery_date']

drop_statuses = ['canceled', 'unavailable']

df3 = df3[~(
    (df3['order_status'].isin(drop_statuses)) & (df3['order_delivered_timestamp'].isnull())
)]

In [133]:
df3['order_delivered_timestamp'].isnull().groupby(df3['order_status']).sum()

order_status
approved      0
canceled      0
delivered     0
invoiced      0
processing    0
shipped       0
Name: order_delivered_timestamp, dtype: int64